export const ENV_VAR_MOCHA_CWD = "VSCODE_TEST_CLI_MOCHA_CWD";
export const ENV_VAR_MOCHA_CONFIG_PATH = "VSCODE_TEST_CLI_MOCHA_CONFIG_PATH";
export const ENV_VAR_NYC_CWD = "VSCODE_TEST_CLI_NYC_CWD";
export const ENV_VAR_NYC_CONFIG_PATH = "VSCODE_TEST_CLI_NYC_CONFIG_PATH";
export const ENV_VAR_BASE_TEST_PATH = "VSCODE_TEST_CLI_BASE_TEST_PATH";
